package com.lianren.android.basicData.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.lianren.android.improve.bean.BasicBean;

import com.lianren.android.basicData.db.BasicBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig basicBeanDaoConfig;

    private final BasicBeanDao basicBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        basicBeanDaoConfig = daoConfigMap.get(BasicBeanDao.class).clone();
        basicBeanDaoConfig.initIdentityScope(type);

        basicBeanDao = new BasicBeanDao(basicBeanDaoConfig, this);

        registerDao(BasicBean.class, basicBeanDao);
    }
    
    public void clear() {
        basicBeanDaoConfig.clearIdentityScope();
    }

    public BasicBeanDao getBasicBeanDao() {
        return basicBeanDao;
    }

}
